### PR TITLE
Change UpdateFields properties to be nullable

### PR DESCRIPTION
**Pull request by BAndysc**
Changed UpdateField types so that their properties with simple types are now nullable, to better reflect what they actually store: when the value is not send by the server, the field will be null.

Also, update handlers **no longer modify existing global data**, instead they return an object with updated fields and those are later merged with the global object storage.

Use with: https://github.com/Shauren/wow-tools/pull/8

Tested with:
4.3.4, 6.2.3, 7.2.5, 7.3.5, 8.1.5, 8.2.0, 8.2.5, 9.0.1 both txt and sql output, all are equal

### CODE REVIEW

**Comment by MaxtorCoder** [comment]
System.Nullable??????? Excuse me.

**Comment by mdX7** [comment]
> System.Nullable??????? Excuse me.

Theres a more nice way to actually suggest stuff @MaxtorCoder. Theres even the option to explain why something should be used or not..

**Comment by MaxtorCoder** [comment]
> > System.Nullable??????? Excuse me.
> 
> Theres a more nice way to actually suggest stuff @MaxtorCoder. Theres even the option to explain why something should be used or not..

He used the correct way before xddd

**Comment by Shauren** [comment]
Autogenerated code, if you want `int?` instead of `System.Nullable<int>` then go submit a PR to microsoft to change what `System.CodeDom.Compiler.CodeDomProvider.GetTypeOutput` returns

**Comment by BAndysc** [comment]
> Autogenerated code, if you want `int?` instead of `System.Nullable<int>` then go submit a PR to microsoft to change what `System.CodeDom.Compiler.CodeDomProvider.GetTypeOutput` returns

Exactly, thanks for the comment 😅 

---

Overall, is this approach fine? Can I proceed with adjusting old handlers to nullable?

**Comment by Shauren** [comment]
Yeah this is fine

**Comment by BAndysc** [comment]
- Upgraded older handlers for nullable fields
- Compared TXT and SQL output for sniffs with versions `4.3.4, 6.2.3, 7.2.5, 7.3.5, 8.1.5, 8.2.0, 8.2.5, 9.0.1` - before and after PR - they are equal

So from my side it is ready to be merged

**Comment by MaxtorCoder** [comment]
Sounds good, and my apologies for my earlier comments 😄👍🏼

**Pull request merged**
