### PR TITLE
Fix phase parsing

### PR DESCRIPTION
**Pull request by LuigiElleBalotta**
Branch: vincent_beta

When parsing legion sniff i observed that a spawn had phaseID concatenated with " - " string. So i needed manually to split that value and create new rows. Now the program do this task.

### CODE REVIEW

**Comment by LuigiElleBalotta** [comment]
is ok now? @DDuarte

**Comment by DDuarte** [comment]
yep, now you won't have issues if you update your own `vincent_beta` branch like it happened with your two previous PRs

**Comment by LuigiElleBalotta** [comment]
Thanks :)

**Comment by LuigiElleBalotta** [comment]
I have to correct PR after I get an answer to this https://community.trinitycore.org/topic/13234-phases/

**Comment by LuigiElleBalotta** [comment]
Moved here: https://github.com/TrinityCore/WowPacketParser/pull/289

**Pull request closed without merging**
