### PR TITLE
Add SQL output for scenes

### PR DESCRIPTION
**Pull request by funjoker**
Added SQL output for Scenes.
Due to no linking of SceneId and SceneScriptPackageID inside DB2.

This will be needed to make Scenes working in future.

### CODE REVIEW

**Comment by DDuarte** [comment]
Update the 5.4.0 SMSG_PLAY_SCENE pretty please (HandleUnknown425)

**Comment by funjoker** [comment]
Okay

**Comment by funjoker** [comment]
Is the HandleUnknown425 function working properly?
Can you maybe provide me a parsed SMSG_PLAY_SCENE part ?

**Comment by funjoker** [comment]
Some Failures here sorry :D

**Pull request closed without merging**
