### PR TITLE
Define new areatrigger type 5

### PR DESCRIPTION
**Pull request by Selenium**
Add Areatrigger type Circle

### CODE REVIEW

**Comment by mdX7** [comment]
when was this introduced?

**Comment by Shauren** [comment]
Is this the CircularMovement type that was placed in flags instead?

**Comment by Selenium** [comment]
Yes, it was used for Chi Sphere on monk before and now use the flags

**Comment by Shauren** [comment]
Then this PR is useless because type isn't sent as a single field in any packet and is our own custom creation

**Pull request closed without merging**
