### PR TITLE
Fix Monster Movement packet parsing

### PR DESCRIPTION
**Pull request by killerwife**
Please verify the actual location of the bit. I used a very unscientific method for it. Fixed my parsing, I assume it will be added in 9.2.

### CODE REVIEW

**Comment by mdX7** [comment]
its in 9.2.0 and even already fully named in tc since the field got added in shadowlands

**Comment by killerwife** [comment]
Please keep in mind this affect 2.5.3 and not 2.5.2 and earlier. 2.5.2 parsed fine for me.

**Comment by mdX7** [comment]
> Please keep in mind this affects 2.5.3 and not 2.5.2 and earlier. 2.5.2 parsed fine for me when i tested without it.

2.5.1 and 2.5.3 are also affected, i checked downto 1.13.6

**Comment by killerwife** [comment]
How the hell did my previous ctbc sniffs parse ok then :D

**Comment by mdX7** [comment]
its just a bit. To read a bit we always have to read an entire byte and then use logical operations to retrieve the actual info. If some bits arent used it doesnt affect the rest of the parse

**Pull request merged**
