### PR TITLE
Some Pet Opcodes

### PR DESCRIPTION
**Pull request by funjoker**
Some Structs for PetOpcodes

### CODE REVIEW

**Comment by funjoker** [comment]
I can only approve this structs for legion

**Comment by funjoker** [comment]
```
         [Parser(Opcode.SMSG_PET_SLOT_UPDATED)]
         public static void HandlePetSlotUpdated(Packet packet)
         {
             packet.ReadInt32("FirstPetNumber");
             packet.ReadInt32("MovedFirstToSlot");
             packet.ReadInt32("SecondPetNumber");
             packet.ReadInt32("MovedSecondToSlot");
         }
```

**Comment by Shauren** [comment]
Please use the original names - https://gist.github.com/Shauren/310fe3f1fcbadc74e102

```
    class PlayerCliSetPetSlot
    {
        ObjectGuid StableMaster;
        uint32 PetNumber = 0;
        uint8 DestSlot = 0;
    };
    class ClientPetSlotUpdated
    {
        int32 PetSlotA = 0;
        int32 PetNumberB = 0;
        int32 PetNumberA = 0;
        int32 PetSlotB = 0;
    };
    class ClientPetStableResult
    {
        uint8 Result = 0;
    };
    class PlayerCliRequestStabledPets
    {
        ObjectGuid StableMaster;
    };
```

**Comment by funjoker** [comment]
ok will do it

**Comment by AndralJu** [comment]
@funjoker where i can have a sniffer 7.3 ? i should take the https://github.com/Zedron/SzimatSzatyor2 one and make an update on it? thx

**Comment by mdX7** [comment]
checked 6.0.3.19103, structs are the same there. Couldn't check SMSG_PET_SLOT_UPDATED tho, opcodenr specified in WPP is a CMSG (0x0B26). (didn't find correct nr on the fly)
PetStableResult enum is also correct. Checked 6.0.3.19103, 7.1.0.22950, 7.2.5.24742, 7.3.0.25195.
But it changed a bit in > 7.3.2 - checked 7.3.2.25549:
`STABLE_ERR_INVALID_SLOT` is `0x2` instead of `0x3`, rest fits still.

**Pull request merged**
