### PR TITLE
Fix some bugs due to recent additions and certain options

### PR DESCRIPTION
**Pull request by killerwife**

### CODE REVIEW

**Comment by jackpoz** [comment]
Could use ?. and ?? operators

**Comment by killerwife** [comment]
You mean packet.Writer?.ToString() ?? ""      ? 

I just really dont like that reading wise :D

**Comment by Fabi** [comment]
> You mean packet.Writer?.ToString() ?? "" ?
> 
> I just really dont like that reading wise :D

Personal preference most likely but a `packet.Writer?.ToString() ?? ""` really makes it way nicer to read. Obviously we are at the "if you know what it does thing", but that would not be a valid reason against using things.

And if you do not like using duplicate code for such things at many places either you can just create an extension method like `public static string ToStringSomething(this StringBuilder sb) => sb?.ToString() ?? "";` too :D

**Comment by killerwife** [comment]
I have a hot take, instead of hiding the implementation behind a member static function, make the field nullable so everyone knows it can be null :D

**Comment by killerwife** [comment]
Snarky comments aside, force pushed with the syntax adjustment.

**Pull request merged**
