### PR TITLE
Add very rudimentary 3.4.1 parsing support

### PR DESCRIPTION
**Pull request by killerwife**

### CODE REVIEW

**Comment by neifion-00000000** [comment]
any chance the missing ones can be added into this too?

47720 48340 49345 and current is 49822

**Comment by killerwife** [comment]
Poached from https://github.com/ratkosrb/WowPacketParser/blob/classic/WowPacketParser/Enums/Version/V3_4_1_47014/Opcodes.cs

**Comment by killerwife** [comment]
@neifion-00000000 filled out 3 missing ones per ymir releases builds.

**Comment by heyitsbench** [comment]
47966, 48019, 48120, 48340, and 48632 were also PTR builds. There might be more, but those I have packets from.

**Comment by neifion-00000000** [comment]
> 47966, 48019, 48120, 48340, and 48632 were also PTR builds. There might be more, but those I have packets from.

oh yeah, I didn't know there was a differentiation between PTR and live parsing but if so those are needed too (all PTR builds that had sniffing had live builds as well)

**Comment by heyitsbench** [comment]
They don't need any special treatment, but the comments for the builds should be adjusted.

**Comment by Vanheden** [comment]
Any update on this?

**Comment by Aokromes** [comment]
Conflicting files
WowPacketParser/Enums/Version/Opcodes.cs

**Comment by neifion-00000000** [comment]
is there some way to sniff the PTR?  I mean doesn't matter much at this point but I've been putting a lot of projects off

**Comment by killerwife** [comment]
No since no realms are available atm.

**Comment by neifion-00000000** [comment]
PTR is up, but ymir is usually updated with PTR only when it matches live versions (and seems to be the case here too)

**Comment by Shauren** [comment]
Merging even if this is almost definitely not 100% correct

**Pull request merged**
