### PR TITLE
Added possibility to generate sql files for creature_queststarter, cr…

### PR DESCRIPTION
**Pull request by mdX7**
…eature_questender, gameobject_queststarter, gameobject_questender

I'd suggest to use only one option in config to enable all 4 of them, but currently i used 4 individual options.
Any opinions on this?

### CODE REVIEW

**Comment by acidmanifesto** [comment]
imo, setting them as individual options is the right path incase of instances of selective parsing, it will cut down on any excess parsing that people are not targeting.

**Comment by Naddley** [comment]
I would suggest to put it into two options: Creature_queststarter & ender as one option and Gameobject_queststarter & ender as the other Option.
In most of the cases you need both (starter & ender) so why splitt into 4 :D

**Comment by mdX7** [comment]
todo: SMSG_QUEST_GIVER_QUEST_LIST_MESSAGE

**Comment by mdX7** [comment]
leaving it as 4 individual options, opinions were widely spread; so just keeping it up using the way we do it for all tables atm

**Pull request merged**
