### PR TITLE
Fixed SMSG_PLAYER_CHOICE_CLEAR struct for 10.0.7

### PR DESCRIPTION
**Pull request by SargeroDeV**
ToDo: 
* Check in which build was the opcode structure changed. Because maybe the opcode structure has changed before, but I don't know which was the exact build in which it was modified, so I left the build of my sniff, since my .exe is from a more advanced build.

### CODE REVIEW

**Comment by Shauren** [comment]
In my opinion new structures with all fields "unk" arent very useful

**Comment by SargeroDeV** [comment]
> In my opinion new structures with all fields "unk" arent very useful

My opinion is different from yours, because I do not play in Retail, so I am not the one who makes the sniffs, I simply take a sniff and open my IDA, I look for its structure and then I test it in the parser, I know that an unnamed structure has no use to work in the core directly, but I give the possibility that any contributor who plays in Retail and does not know Reverse Engineering himself can take that structure and according to his sniff data he can rename the fields.

**Comment by Shauren** [comment]
Ah but you see, thats the issue here, you don't guess names based on sniff data but rather by what client does with them - so your imaginary contributor (that will be doing the rename) still needs to know how to reverse

**Comment by SargeroDeV** [comment]
This is not necessary for all types

**Pull request closed without merging**
