### PR TITLE
Fix reading BitVectors after 11.0.5 changes

### PR DESCRIPTION
**Pull request by Christyan**
Before:
kép

After:
kép

Thanks for the hard work

### CODE REVIEW

**Comment by MaxtorCoder** [comment]
What. This makes no sense???

**Comment by Christyan** [comment]
Which part? This function changed in the 11.0.5 client.

**Comment by Christyan** [comment]
Ohh copypasta typo, i reopen it

**Comment by MaxtorCoder** [comment]
Just push the fix…? No need to open a new PR lol

**Pull request closed without merging**
