### PR TITLE
Fix SMSG_SPELL_INTERRUPT_LOG

### PR DESCRIPTION
**Pull request by funjoker**

### CODE REVIEW

**Comment by soulfrost** [comment]
@funjoker wrong order, check this

ServerToClient: SMSG_SPELL_INTERRUPT_LOG (0x2C20) Length: 31 ConnIdx: 0 Time: 08/14/2018 06:15:54.828 Number: 2272144
Caster: Full: 0x081E2400000000000000000003F0E477; HighType: Player; Low: 66118775; Map: 0
Victim: Full: 0x20309CCD607FC200000F8A0000726CA4; HighType: Creature; Low: 7498916; Map: 1643; Entry: 130824;
InterruptedSpellID: 96231 (96231)
SpellID: 157534 (157534)


ServerToClient: SMSG_SPELL_INTERRUPT_LOG (0x2C20) Length: 30 ConnIdx: 0 Time: 08/14/2018 05:50:58.328 Number: 2201287
Caster: Full: 0x0819080000000000000000000840040C; HighType: Player; Low: 138413068; Map: 0
Victim: Full: 0x203AF4E90082EB000032D3000072697F; HighType: Creature; Low: 7498111; Map: 1864; Entry: 134060;
InterruptedSpellID: 31935 (31935)
SpellID: 268347 (268347)


first spell id is spell which had interrupt effect

**Comment by funjoker** [comment]
Learn english @soulfrost

**Comment by soulfrost** [comment]
learn how to check sniffs

**Comment by mdX7** [comment]
268347 is Voidbolt, the interupted spell
31935 is Avenger's Shield, the INTERRUPTING spell/the kickspell/whatever you want to call it

Avenger's Shield silences and silence is equal to interrupt.
=> funjoker is correct

**Comment by funjoker** [comment]
`Interrupt != Interrupted`

**Comment by soulfrost** [comment]
ah fuck, mine mistake, too absent this morning, sry

**Comment by funjoker** [comment]
Lets clear the history just delete everything xD

**Pull request merged**
